### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name":"Aniket kafka",
    "email":"textkafka202789@gmail.com",
    "address":"pune street 45",
    "dateOfBirth":"2001-10-25",
    "updatedRegisterDate":"2025-10-19"
}
###